name: Deploy to Render

on:
  push:
    branches:
      - master  # Change to "main" if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Render Deploy Hook
        run: |
          curl -X GET https://api.render.com/deploy/srv-cuhssfaj1k6c73fdktd0?key=fASpehKKPlw

    env:
      RENDER_DEPLOY_HOOK: https://api.render.com/deploy/srv-cuhssfaj1k6c73fdktd0?key=fASpehKKPlw
